name: humseafood
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  smooth_page_indicator: ^0.2.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.6+1
  curved_navigation_bar: ^0.3.4
  toast: ^0.1.5
  intl: ^0.16.1
  google_maps_flutter: ^0.5.21+17
  location: ^3.0.2
  geolocator: ^5.3.2+2
  firebase_storage: any
  cloud_firestore: any
  path: any
  provider: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/icons/
    - assets/images/onboarding_images/
    - assets/images/placeholder.jpg
    - assets/images/loading.gif
    - assets/images/nodata.jpg
  fonts:
    - family: BalooTamma2
      fonts:
        - asset: assets/fonts/BalooTamma2-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
